'use client'
import{useEffect,useState}from'react'
import{useRouter}from'next/navigation'
import{ApiError,createStoreOrder,getDeliveryOptions,getMe,quoteCart}from'@/lib/api'
import type{CartItem,CartQuote,Customer,DeliveryOption}from'@/lib/types'
import{track}from'@/lib/analytics'
import{openRazorpayCheckout}from'@/lib/razorpay'
import{OtpLogin}from'@/components/my/otp-login'
const CART_KEY='livenza_store_cart_v1'
function money(minor:number,currency='INR'){return new Intl.NumberFormat('en-IN',{style:'currency',currency}).format(minor/100)}
function loadItems():CartItem[]{try{const p=JSON.parse(localStorage.getItem(CART_KEY)||'[]');return Array.isArray(p)?p.map((x:any)=>({variant_id:Number(x?.variant_id),quantity:Number(x?.quantity)})).filter(x=>x.variant_id>0&&x.quantity>0):[]}catch{return[]}}
export default function CheckoutView(){const router=useRouter();const[items,setItems]=useState<CartItem[]>([]);const[quote,setQuote]=useState<CartQuote|null>(null);const[customer,setCustomer]=useState<Customer|null>(null);const[deliveryOptions,setDeliveryOptions]=useState<DeliveryOption[]>([]);const[deliveryMode,setDeliveryMode]=useState<'address'|'property_room'>('address');const[selectedDelivery,setSelectedDelivery]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[name,setName]=useState('');const[line1,setLine1]=useState('');const[city,setCity]=useState('');const[state,setState]=useState('');const[postal,setPostal]=useState('')
 useEffect(()=>{const cart=loadItems();setItems(cart);if(cart.length)quoteCart(cart).then(setQuote).catch(e=>setError(e instanceof Error?e.message:'OUT_OF_STOCK'));getMe().then(r=>{setCustomer(r.customer);getDeliveryOptions().then(setDeliveryOptions).catch(()=>setDeliveryOptions([]))}).catch(()=>undefined)},[])
 async function pay(){if(!customer||!items.length||!quote)return;setBusy(true);setError('');track('checkout_start',{total_minor:quote.total_minor});try{const refreshed=await quoteCart(items);setQuote(refreshed);const result=await createStoreOrder({items,delivery_mode:deliveryMode,delivery:deliveryMode==='property_room'?{delivery_option_id:selectedDelivery}:{recipient_name:name||customer.full_name,line1,city,state,postal_code:postal}});if(result.order.status!=='placed')throw new Error('Order could not enter payment state.');await openRazorpayCheckout({key:result.checkout.key_id,amount:result.checkout.amount_minor,currency:result.checkout.currency,order_id:result.checkout.order_id,name:'Livenza.store',description:`Order ${result.order.id}`,handler:()=>router.push(`/store/order/${result.order.id}`),modal:{ondismiss:()=>setBusy(false)},prefill:{name:name||customer.full_name,contact:customer.primary_mobile},theme:{color:'#e86f2a'}})}catch(e){setBusy(false);if(e instanceof ApiError&&e.code==='OUT_OF_STOCK')setError('OUT_OF_STOCK — refresh your bag before continuing.');else setError(e instanceof Error?e.message:'Checkout could not start.')}}
 if(!customer)return <div className="store-checkout"><div><span className="store-kicker">CHECKOUT</span><h1>One Livenza ID.</h1><p>Sign in with the same mobile number you use for stays and My Livenza.</p><OtpLogin onAuthenticated={setCustomer}/></div></div>
 return <div className="store-checkout"><div><span className="store-kicker">DELIVERY</span><h1>Where should it go?</h1>{error?<div className="store-error">{error}</div>:null}{deliveryOptions.length?<div className="store-delivery-tabs"><button data-selected={deliveryMode==='address'} onClick={()=>setDeliveryMode('address')}>Another address</button><button data-selected={deliveryMode==='property_room'} onClick={()=>{setDeliveryMode('property_room');setSelectedDelivery(current=>current||deliveryOptions[0]?.id||'')}}>Deliver to my Livenza property</button></div>:null}{deliveryMode==='property_room'?<label>Livenza property<select value={selectedDelivery} onChange={(e:any)=>setSelectedDelivery(e.target.value)}>{deliveryOptions.map(option=><option value={option.id} key={option.id}>{option.label}</option>)}</select></label>:<><label>Recipient<input value={name} onChange={(e:any)=>setName(e.target.value)} placeholder={customer.full_name||'Your name'}/></label><label>Address<input value={line1} onChange={(e:any)=>setLine1(e.target.value)} /></label><div className="store-form-row"><label>City<input value={city} onChange={(e:any)=>setCity(e.target.value)}/></label><label>State<input value={state} onChange={(e:any)=>setState(e.target.value)}/></label></div><label>PIN code<input value={postal} onChange={(e:any)=>setPostal(e.target.value)}/></label></>}</div>{quote?<aside className="store-summary"><span>TOTAL</span><strong>{money(quote.total_minor,quote.currency)}</strong><button className="store-primary" disabled={busy||(deliveryMode==='address'&&(!line1||!city||!postal))||(deliveryMode==='property_room'&&!selectedDelivery)} onClick={pay}>{busy?'OPENING PAYMENT…':'PAY SECURELY'}</button><small>Final price and stock are rechecked immediately before the order is created.</small></aside>:<aside className="store-summary">Your bag needs a fresh quote before checkout.</aside>}</div>
}
