begin;

alter table public."user" add column if not exists pattern_hash text default '';
alter table public."user" add column if not exists webauthn_enabled boolean not null default false;
alter table public."user" add column if not exists webauthn_enrolled_at timestamp null;

create table if not exists public.web_authn_credential (
  id integer generated by default as identity primary key,
  user_id integer not null references public."user"(id) on delete cascade,
  credential_id bytea not null unique,
  public_key bytea not null,
  sign_count bigint not null default 0 check (sign_count >= 0),
  transports text not null default '[]',
  device_name varchar(180) not null default 'Windows Hello / fingerprint',
  created_at timestamp not null default timezone('utc', now()),
  last_used_at timestamp null
);

create table if not exists public.whatsapp_message (
  id integer generated by default as identity primary key,
  direction varchar(12) not null default 'outbound' check (direction in ('inbound','outbound')),
  contact_name varchar(180) not null default '',
  wa_id varchar(40) not null default '',
  message_id varchar(220) unique,
  message_type varchar(40) not null default 'text',
  body text not null default '',
  status varchar(40) not null default 'sent',
  raw_json text not null default '{}',
  created_at timestamp not null default timezone('utc', now())
);

create table if not exists public.drive_file (
  id integer generated by default as identity primary key,
  provider_file_id varchar(220) not null unique,
  name varchar(300) not null,
  mime_type varchar(180) not null default 'application/octet-stream',
  file_size bigint not null default 0 check (file_size >= 0),
  web_view_link text not null default '',
  source varchar(80) not null default 'manual',
  uploaded_by_user_id integer references public."user"(id) on delete set null,
  created_at timestamp not null default timezone('utc', now())
);

create index if not exists idx_web_authn_credential_user_id on public.web_authn_credential(user_id);
create index if not exists idx_whatsapp_message_wa_created on public.whatsapp_message(wa_id, created_at desc);
create index if not exists idx_whatsapp_message_created_at on public.whatsapp_message(created_at desc);
create index if not exists idx_drive_file_uploaded_by on public.drive_file(uploaded_by_user_id);

alter table public.web_authn_credential enable row level security;
alter table public.whatsapp_message enable row level security;
alter table public.drive_file enable row level security;

revoke all on table public.web_authn_credential from anon, authenticated;
revoke all on table public.whatsapp_message from anon, authenticated;
revoke all on table public.drive_file from anon, authenticated;

commit;
