'use client'
import{useEffect,useState}from'react'
import Link from'next/link'
import{createParentPayment,getMe}from'@/lib/api'
import type{Customer}from'@/lib/types'

type RazorpayInstance={open:()=>void};type RazorpayCtor=new(options:Record<string,unknown>)=>RazorpayInstance
declare global{interface Window{Razorpay?:RazorpayCtor}}
async function loadRazorpay(){if(window.Razorpay)return;await new Promise<void>((resolve,reject)=>{const script=document.createElement('script');script.src='https://checkout.razorpay.com/v1/checkout.js';script.async=true;script.onload=()=>resolve();script.onerror=()=>reject(new Error('Payment checkout could not load'));document.head.appendChild(script)})}
export function ParentSharePayment({token,bookingId}:{token:string;bookingId:string}){const[customer,setCustomer]=useState<Customer|null>(null);const[checked,setChecked]=useState(false);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');useEffect(()=>{getMe().then(r=>setCustomer(r.customer)).catch(()=>undefined).finally(()=>setChecked(true))},[]);async function pay(){if(busy)return;setBusy(true);setMessage('');try{const result=await createParentPayment(token);await loadRazorpay();if(!window.Razorpay)throw new Error('Payment checkout is unavailable.');new window.Razorpay({key:result.checkout.key_id,amount:result.checkout.amount_minor,currency:result.checkout.currency,order_id:result.checkout.order_id,name:'Livenza.life',description:`Booking ${bookingId}`,handler:()=>{setMessage('Payment submitted. The booking will update after secure gateway confirmation.');setBusy(false)},modal:{ondismiss:()=>setBusy(false)},prefill:{name:customer?.full_name||'',contact:customer?.primary_mobile||''}}).open()}catch(e){setBusy(false);setMessage(e instanceof Error?e.message:'Payment could not start.')}}if(!checked)return <p>Checking sign-in…</p>;if(!customer)return <div><p>Sign in with your own mobile number before paying this shared booking.</p><Link className="ecosystem-primary" href={`/account?next=${encodeURIComponent(`/stays/share/${token}`)}`}>SIGN IN TO APPROVE</Link></div>;return <div><button className="ecosystem-primary" onClick={pay} disabled={busy}>{busy?'OPENING PAYMENT…':'Approve & Pay'}</button>{message?<p>{message}</p>:null}</div>}
